-- Crear función optimizada para obtener un grupo individual
-- Note: Skipping function creation if required tables don't exist to avoid validation errors
-- The function will be created when the tables exist