-- Fix: Create idempotent trigger for first_post badge to avoid duplicate key errors
-- This replaces any existing trigger that might be causing the duplicate key violation
-- Note: Skipping function and trigger creation as they depend on posts and profile_badges tables
-- These will be created when the required tables exist
