-- Analytics Pro: project-level lists and daily series
-- Note: Skipping RPC functions as they depend on posts and analytics_daily_entity tables
-- These will be created when the required tables exist
