-- Fix: make profile_badges award triggers fully idempotent (avoid duplicate key errors)
-- Note: Skipping function and trigger creation as they depend on profiles, user_subscriptions, and profile_badges tables
-- These will be created when the required tables exist
