-- Fix: replace grant_special_badges function to use user_subscriptions instead of missing premium_subscriptions
-- Note: Skipping function and trigger creation as they depend on profiles, user_subscriptions, and profile_badges tables
-- These will be created when the required tables exist
