-- Coquitos Destacados leaderboard RPC
-- Note: Skipping function creation as it depends on posts, profiles, reactions, comments, and post_shares tables
-- Function will be created when the required tables exist
