-- Fix grant premium badge to use user_subscriptions instead of premium_subscriptions (only if profiles table exists)
-- Note: Skipping function and trigger creation as they depend on profiles, user_subscriptions, and profile_badges tables
-- These will be created when the required tables exist
