-- Send automatic DM after publishing an idea (runs with elevated privileges)
-- Note: Skipping function creation as it depends on canales, miembros_canal, and mensajes tables
-- Function will be created when the required tables exist
