-- Update analytics RPC to include technologies field
-- Note: Skipping function creation as it depends on posts and analytics_daily_entity tables
-- This will be created when the required tables exist
