-- Fix: prevent duplicate profile_badges inserts from breaking post/project creation
-- Some legacy triggers/functions may INSERT without ON CONFLICT, which can violate
-- unique constraint profile_badges_profile_id_badge_type_key.
-- Note: Skipping function and trigger creation as they depend on profile_badges table
-- This will be created when the required table exists
