// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Enhanced error validation with detailed debugging information
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorDetails = {
    environment: import.meta.env.MODE,
    supabaseUrl: SUPABASE_URL ? 'SET' : 'MISSING',
    supabaseKey: SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING',
    allEnvVars: Object.keys(import.meta.env).filter(key => key.startsWith('VITE_'))
  };
  
  console.error('Supabase Configuration Error:', errorDetails);
  
  throw new Error(
    `Missing Supabase environment variables. ` +
    `VITE_SUPABASE_URL: ${SUPABASE_URL ? 'SET' : 'MISSING'}, ` +
    `VITE_SUPABASE_ANON_KEY: ${SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING'}. ` +
    `Environment: ${import.meta.env.MODE}. ` +
    `Available VITE_ variables: ${errorDetails.allEnvVars.join(', ')}. ` +
    `Please ensure these variables are set in your deployment platform (Render).`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
  },
  db: {
    schema: 'public',
  },
});